# -*- coding: utf-8 -*-
"""BreastCancerDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ySCQJmx7129kY2D41HKtWwr7kHp9D4th
"""

import pandas as pd
import matplotlib.pyplot as plt


data = pd.read_csv("data.csv")

data['diagnosis']= data['diagnosis'].replace(["B","M"],[2,1],regex=True)

X = data.iloc[:, 1:31].values
Y = data.iloc[:, 31].values

print(X)

#Encoding categorical data values
from sklearn.preprocessing import LabelEncoder
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)





#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10,criterion ="entropy",random_state = 0)
classifier.fit(X_train,Y_train)

Y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test,Y_pred)
print(cm) 
print(accuracy_score(Y_train, classifier.predict(X_train))*100)

cv = pd.DataFrame(cm)
cv